### ISSUE TITLE
No Dockerfile

### ISSUE THREAD

**Issue by karnauskas** [private-vault/vault#7]

**Comment by ValdasK** [comment]
What do you mean by that? This project uses Docker Compose to run (it consists of several dockerfiles); and sample can be found at `docker-compose.yml.dist`

**Comment by karnauskas** [comment]
docker-compose.yml.dist this file specifies exactly 5 images to use to run project (or the part of it), but none of those are used to prepare docker image

**Comment by ValdasK** [comment]
For development, all 5 containers are used, as each one of them provides single resource, and volumes are mounted from host system for instant changes.

For production, we do not recommend to use Docker (and if you do, use dedicated host volumes), because losing encryption key stored in `.env` file or database will make secrets unrecoverable.
